### ISSUE TITLE
Version 0.7.1 on Anaconda? CGAL support for periodic boundary conditions?

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#194]
I was wondering what the best way (if any) to install the versions 0.7.x on Anaconda with CGAL support? If not what version should I use if I want to implement periodic boundary conditions in 2D? 

Thank you.

**Comment by glyg** [comment]
Hi @sniffo, if you're using windows it is not super easy, because I can't for the life of me have Azure compile correctly for Windows OS. I'll try to get it another try soon. 

I think if you use pip you have a 0.7 version for windows, but without CGAL support. Note that CGAL is not necessary for computation with periodic boundaries, just for generation of PBC tissues. 

Maybe @gcourcou can comment as he did a great work on PBC some time ago with PR #167 ?

**Comment by gcourcou** [comment]
Dear DamCB/tyssue community and @sniffo ,

Exactly as Guillaume mentioned, CGAL is indeed optional. You will not have the collision detection algorithm (triggered when tissue self intersects) but all other operations should be fine. For my computations, I import a ready periodic tissue created by Guillaume with CGAL and go from there. I have not generated my own periodic tyssue file.

There is a test file for PBC at tyssue/tests/solvers/test_periodic_sheet.py that loads the periodic file correctly. You can copy the commands and go from there. 

Finally, the current implementation is only for square tissues: The Lx and Ly box size dimensions grow together. To that end, I have implemented a newer version in my forked directory (needs polishing) that deals with rectangle rather than only square PBC. 

Best,
George Courcoubetis

**Comment by glyg** [comment]
Thanks for the input George

**Comment by sniffo** [comment]
Thank you, Guillaume and George! 

@gcourcou would love to hear any updates on the rectangular implementation when available. Also, can PBC be applied to non-periodic tissue objects (does not make a lot of sense to me to do so, but Guillaume mentioned it was possible)?

**Comment by glyg** [comment]
>  (does not make a lot of sense to me to do so, but Guillaume mentioned it was possible)?

Did I?

I don't see how this would be usefull either :sweat_smile: 

G.

**Comment by sniffo** [comment]
Closed it by mistake. Looking forward to George's eventual updates on rectangular periodic tissues.

**Comment by gcourcou** [comment]
[quasistatic.py.zip](https://github.com/DamCB/tyssue/files/4861815/quasistatic.py.zip)

**Comment by sniffo** [comment]
Hi @gcourcou, I understand that this is edited to solve rectangular periodic tissues as well? Any clue how to generate such a tissue? 

Best, 
Tasnif

**Comment by gcourcou** [comment]
Hello fellow human Tasnif. You can start from square tissue . That is the only file I have used! E.g. Biasing on your angles of division you could make cells divide and end up with a more rectangular tissue. What are you trying to do?

**Comment by sniffo** [comment]
Hi George! I am trying to expand data we have from rectangular micropatterns to a larger tissue using the PBC. The strategy you have outlined should work for this purpose. Thanks!
