### ISSUE TITLE
T1 Transitions and Collision - Quasistatic and Viscous Solvers

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#211]
Are T1 transitions automatically performed based on the threshold length in eptm.settings? It's not obvious from looking at the simulations themselves. Thanks!

**Comment by sophietheis** [comment]
Yes, in both quasistatic or viscous solver T1 are performed based on the threshold length in eptm.settings if you configure correctly the solver (e.g. put `auto_reconnect=True` for viscous solver, or `with_t1=True` for quasistatic solver).

**Comment by sniffo** [comment]
Perfect, thank you!

**Comment by sniffo** [comment]
Sorry to bring this issue back from the dead, but does there exist a strategy to quantify the number of times T-1 transitions that occur during a particular experiment?

**Comment by sophietheis** [comment]
I think the strategy will be to looking for change in neighbouring cell. Maybe @glyg has already something to track T1 transition ?

**Comment by glyg** [comment]
Hi,
I don't have anything ready, you can use the `topo_changed` flag to detect them (see e.g. https://github.com/DamCB/tyssue/blob/e2556eae5bca87e2349ec7700a15e74f48b0a8bc/tyssue/solvers/quasistatic.py#L114) I also realize that there should be much more logging being done in those topology function, so that we can use the logs for that kind of things. There is some logging being done in the viscous solver, and in the quasistatic solver, the `num_restart` attribute is incremented each time there is a topology change.


It might be good to add some kind of mechanism in `History` for that

**Comment by sophietheis** [comment]
Some answer in  issue #239
