### ISSUE TITLE
Random addition of vertices fails for internal cells

### ISSUE THREAD

**Issue by jonathan-f** [DamCB/tyssue#252]
Hello,
I am starting from a tissue with all hexagonal cells and my goal is to recursively add vertices to generate heptagonal and octagonal cells. However, this works only for outermost edges (those that are "unique"), while for duplicated edges (those forming the boundary between two cells) I see that the number of sides of the cell increases when a vertex is added, but this is not seen when plotting the tissue (i.e. the cell stays hexagonal). 

This is my starting tissue (called sheet below):
![Screenshot 2022-01-05 at 16 43 34](https://user-images.githubusercontent.com/54023927/148246108-b4771629-44e3-49a8-9431-37d3a63800b2.png)

This is the code for recursive vertex addition (tyssue v0.7.1):

```
from tyssue import config
from tyssue import Sheet
from tyssue import PlanarGeometry as geom
from tyssue.topology.base_topology import add_vert

import random

model,specs,solver=DefineModel(sheet)
sheet.update_specs(specs, reset=True)

for i in range(10):

    edge_to_merge = random.choices(sheet.edge_df.index, k=1)[0]
    add_vert(sheet, edge_to_merge)
    sheet.update_num_sides()
    sheet.update_rank()
    geom.update_all(sheet)
    res = solver.find_energy_min(sheet, geom, model)      
```

This is the final tissue:
![Screenshot 2022-01-05 at 16 52 12](https://user-images.githubusercontent.com/54023927/148247657-6c6ddf41-72f5-47a1-af66-6ee2b7b6595c.png)

I only see two heptagonal cells, but in sheet.face_df there are many other cells with 7,8 and even 9 sides. Do you have any suggestion on how to fix the problem?

Thanks,
Best
Jonathan

PS

The code for generating the initial configuration is [here](https://github.com/ScialdoneLab/2DLEGI/blob/main/ConfigGenerator.ipynb) if you need.

**Comment by glyg** [comment]
Hi Jonathan,
Glad to hear you're using tyssue :)

You can plot the vertices with `sheet_view(sheet, vertex={"visible": True})`
Maybe you can check where they are added before you  run the gradient descent.  

However I think that after the gradient descent, the extra vertices will not have a clear behavior, because the steady state is a straight edge, so the extra vertices can be anywhere along that edge... Maybe if you had a pressure difference effector or some such thing, the edge will go away from the straight line.

You can use the `plot_forces` function to see what's going on if you define new forces.


Best

Guillaume

**Comment by glyg** [comment]
An easy way to have bent edges would be to put a [`LengthEllasticity`](https://github.com/DamCB/tyssue/blob/60ab0906c8394091e557f4e7998d2aebbb95399c/tyssue/dynamics/effectors.py#L77) effector with a high rest length. Not sure how stable this would all be though

**Comment by jonathan-f** [comment]
Hi Guillaume,
thanks for the advice and the swift reply. I think it is as you wrote, the vertices are correctly added but they do not bend, even without running the gradient descent.

I tried adding a LengthElasticity effector to my model, this is my model definition (s is a sheet object)

```
def DefineModel(s):
    # Define a mechanical model associated to the sheet
    model = model_factory(
        [
        effectors.LineTension,
        effectors.FaceContractility,
        effectors.FaceAreaElasticity,
        effectors.LengthElasticity
        ]
    )
    
    specs = {
        "face": {
        "contractility": 5e-2,
        "prefered_area": s.face_df.area.mean(),
        "area_elasticity": 1.
        },
        "edge": {
        "length_elasticity": 1,
        "prefered_length": 7,
        "line_tension": 1e-2,
        "is_active": 1
        },
        "vert": {
        "is_active": 1
        },
    }
    
    solver = QSSolver()
    
    return model,specs,solver;
```

Starting from this configuration
![Screenshot 2022-01-07 at 11 11 10](https://user-images.githubusercontent.com/54023927/148528880-3ee68bc9-d8c3-44e2-8538-08c741c58595.png)

I played around with "prefered_length" and with 7 I get this one, after the addition of 10 vertices at randomly selected edges:
![Screenshot 2022-01-07 at 11 11 19](https://user-images.githubusercontent.com/54023927/148528946-6ffffc67-a34f-4064-a631-9be69c03a2ed.png)

Now I am closer to the solution since I manage to increase the number of sides of inner cells, but the resulting configuration is much different from the initial one. Is there a way of keeping it more similar?

Otherwise, reverting the problem: do you think it is possible to create a sheet with all octagonal cells (or with aribtrary number of sides), for instance modifying the function planar_sheet_2d? In this way I could then use collapse_edges recursively to generate a mixture of cells with different number of sides, while having a more "ordered" sheet compared to the one I obtain so far.

Thanks
Best
Jonathan

**Comment by glyg** [comment]
Hi Jonathan,

If you want a sheet with octagonal cells, where all the vertices belong to more than 2 cells, you have a [paving](https://en.wikipedia.org/wiki/Tessellation) problem, i.e you cannot have only octagonal cells because you can't pave the plane with octagons. The way `planar_sheet_2d` works is through Voronoï tessalation, which will determine your mesh topology based on the face centers position. If you want a regular tilling, I'm afraid you'd have to code it "by hand". If you find some existing code that generates the tiling in a mesh format (`.obj` or `.ply` for example), It should be possible to create a sheet object from the file (I can help with that if needed).

Best
Guillaume

**Comment by jonathan-f** [comment]
Hi Guillaume,
ok thank you very much, I will try. 

Best
Jonathan

**Comment by glyg** [comment]
Re-reading your previous message, if you "simply" want a less regular distribution of number of sides, you can pass a value to the "noise" argument in planar_sheet_2d, or perform cell divisions with random orientation. Both those will have the effect of producing a distribution of edges
