### ISSUE TITLE
Faces become deformed and can overlap

### ISSUE THREAD

**Issue by Lepinja666** [DamCB/tyssue#269]
I've noticed that sometimes when running a simulation, faces can become weirdly shaped and start overlapping with one another. This doesn't happen often so it's hard to debug it and I'm not sure whether it is a consequence of a cell division, cell death or T1 transition. The resulting tiling looks like this (a couple of examples):

![problematic](https://user-images.githubusercontent.com/113996668/232735660-a23544f4-1bc8-424e-94ee-e183218d90ab.png)

Has anyone ever encountered this and managed to debug it?
Thank you in advance!

**Comment by btbest** [comment]
I had the same thing happening in my simulations, but never dug deeper since I took it as an indication that I have an underlying problem with the sanity of the conditions I'm simulating.

I remember getting import warnings about the collision detection, so it sounded to me like there is some functionality of that kind in tyssue. Although judging by the warnings, it wouldn't have worked for me because I was on Windows and I would've had to figure out how to compile that module for my OS.

Without collision detection, there's nothing constraining your vertices in space besides the energy or force function that you've put on your edges. Sometimes the energy minimiser can drop into a local minimum that doesn't make a lot of sense, even if it is mathematically correct. Since you mention T1 transitions, I take it you modify the graph during the simulation, in which case indeed this could also be a bug due to nonsensical edges coming out of the rearrangements.

In terms of debugging, I never found any other way than to manually identify the ID of the perpetrating face and then backtracing what happened with it throughout the iterations...

**Comment by Lepinja666** [comment]
Thank you both for the extensive answers :) 
The `threshold_length` really does make a big difference. If it is about a third of the average edge length the problem occurs very rarely and if it is about a fifth of the average edge length it occurs in almost every simulation.
